### ISSUE TITLE
timeout not works

### ISSUE THREAD

**Issue by shaoweigege** [FlyinDoji/whois#2]
It seems dial timeout not works

I am testing domain aaa.sb , it will dial for up to 2.2 minutes

**Comment by FlyinDoji** [comment]
I've checked, seems using the default net.Dial function will leave the connection hanging if the whois server doesn't respond. I'll change it to use the Dial function of a custom Dialer struct where I can set the timeout.

**Comment by FlyinDoji** [comment]
Changed the code to use a timeout context when contacting the whois server. I've set it to a reasonable 12 seconds but in the future I'll probably add a way to set it in user code. Both Whois and ProxiedWhois time out properly when testing with "aaa.sb". Thanks for the notice!
